# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/mapreduce.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/mapreduce.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"N\n\x04Task\x12!\n\ttask_type\x18\x01 \x01(\x0e\x32\x0e.grpc.TaskType\x12\n\n\x02id\x18\x02 \x01(\x03\x12\t\n\x01M\x18\x03 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\t*8\n\x08TaskType\x12\x08\n\x04idle\x10\x00\x12\x07\n\x03map\x10\x01\x12\n\n\x06reduce\x10\x02\x12\r\n\tshut_down\x10\x03\x32\x92\x01\n\tMapReduce\x12*\n\x0fget_worker_task\x12\x0b.grpc.Empty\x1a\n.grpc.Task\x12*\n\x0f\x66inish_map_task\x12\x0b.grpc.Empty\x1a\n.grpc.Task\x12-\n\x12\x66inish_reduce_task\x12\x0b.grpc.Empty\x1a\n.grpc.Taskb\x06proto3'
)

_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='grpc.TaskType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='idle', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='map', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='reduce', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='shut_down', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=121,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_TASKTYPE)

TaskType = enum_type_wrapper.EnumTypeWrapper(_TASKTYPE)
idle = 0
map = 1
reduce = 2
shut_down = 3



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='grpc.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_type', full_name='grpc.Task.task_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.Task.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='M', full_name='grpc.Task.M', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='grpc.Task.data', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=119,
)

_TASK.fields_by_name['task_type'].enum_type = _TASKTYPE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.enum_types_by_name['TaskType'] = _TASKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Task)
  })
_sym_db.RegisterMessage(Task)



_MAPREDUCE = _descriptor.ServiceDescriptor(
  name='MapReduce',
  full_name='grpc.MapReduce',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=180,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_worker_task',
    full_name='grpc.MapReduce.get_worker_task',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='finish_map_task',
    full_name='grpc.MapReduce.finish_map_task',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='finish_reduce_task',
    full_name='grpc.MapReduce.finish_reduce_task',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPREDUCE)

DESCRIPTOR.services_by_name['MapReduce'] = _MAPREDUCE

# @@protoc_insertion_point(module_scope)
