# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/mapreduce.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/mapreduce.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x14\n\x06Worker\x12\n\n\x02id\x18\x01 \x01(\x03\"Z\n\x04Task\x12!\n\ttask_type\x18\x01 \x01(\x0e\x32\x0e.grpc.TaskType\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x15\n\rnum_red_tasks\x18\x03 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\t\"\x1d\n\x08WordList\x12\x11\n\tword_list\x18\x01 \x03(\t\"\x86\x01\n\nMapResults\x12\x35\n\x0bmap_results\x18\x01 \x03(\x0b\x32 .grpc.MapResults.MapResultsEntry\x1a\x41\n\x0fMapResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.grpc.WordList:\x02\x38\x01\"\x98\x01\n\rReduceResults\x12>\n\x0ereduce_results\x18\x01 \x03(\x0b\x32&.grpc.ReduceResults.ReduceResultsEntry\x12\x11\n\tbucket_id\x18\x02 \x01(\x05\x1a\x34\n\x12ReduceResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01*8\n\x08TaskType\x12\x08\n\x04idle\x10\x00\x12\x07\n\x03map\x10\x01\x12\n\n\x06reduce\x10\x02\x12\r\n\tshut_down\x10\x03\x32\xd0\x01\n\tMapReduce\x12+\n\x0fget_worker_task\x12\x0c.grpc.Worker\x1a\n.grpc.Task\x12\x35\n\x0f\x66inish_map_task\x12\x10.grpc.MapResults\x1a\x10.grpc.MapResults\x12\x35\n\x12\x66inish_reduce_task\x12\x13.grpc.ReduceResults\x1a\n.grpc.Task\x12(\n\x0bworker_down\x12\x0c.grpc.Worker\x1a\x0b.grpc.Emptyb\x06proto3'
)

_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='grpc.TaskType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='idle', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='map', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='reduce', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='shut_down', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=478,
  serialized_end=534,
)
_sym_db.RegisterEnumDescriptor(_TASKTYPE)

TaskType = enum_type_wrapper.EnumTypeWrapper(_TASKTYPE)
idle = 0
map = 1
reduce = 2
shut_down = 3



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_WORKER = _descriptor.Descriptor(
  name='Worker',
  full_name='grpc.Worker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.Worker.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=61,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='grpc.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_type', full_name='grpc.Task.task_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.Task.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_red_tasks', full_name='grpc.Task.num_red_tasks', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='grpc.Task.data', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=153,
)


_WORDLIST = _descriptor.Descriptor(
  name='WordList',
  full_name='grpc.WordList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word_list', full_name='grpc.WordList.word_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=184,
)


_MAPRESULTS_MAPRESULTSENTRY = _descriptor.Descriptor(
  name='MapResultsEntry',
  full_name='grpc.MapResults.MapResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.MapResults.MapResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.MapResults.MapResultsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=321,
)

_MAPRESULTS = _descriptor.Descriptor(
  name='MapResults',
  full_name='grpc.MapResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_results', full_name='grpc.MapResults.map_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAPRESULTS_MAPRESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=321,
)


_REDUCERESULTS_REDUCERESULTSENTRY = _descriptor.Descriptor(
  name='ReduceResultsEntry',
  full_name='grpc.ReduceResults.ReduceResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.ReduceResults.ReduceResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.ReduceResults.ReduceResultsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=476,
)

_REDUCERESULTS = _descriptor.Descriptor(
  name='ReduceResults',
  full_name='grpc.ReduceResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reduce_results', full_name='grpc.ReduceResults.reduce_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket_id', full_name='grpc.ReduceResults.bucket_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REDUCERESULTS_REDUCERESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=476,
)

_TASK.fields_by_name['task_type'].enum_type = _TASKTYPE
_MAPRESULTS_MAPRESULTSENTRY.fields_by_name['value'].message_type = _WORDLIST
_MAPRESULTS_MAPRESULTSENTRY.containing_type = _MAPRESULTS
_MAPRESULTS.fields_by_name['map_results'].message_type = _MAPRESULTS_MAPRESULTSENTRY
_REDUCERESULTS_REDUCERESULTSENTRY.containing_type = _REDUCERESULTS
_REDUCERESULTS.fields_by_name['reduce_results'].message_type = _REDUCERESULTS_REDUCERESULTSENTRY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Worker'] = _WORKER
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['WordList'] = _WORDLIST
DESCRIPTOR.message_types_by_name['MapResults'] = _MAPRESULTS
DESCRIPTOR.message_types_by_name['ReduceResults'] = _REDUCERESULTS
DESCRIPTOR.enum_types_by_name['TaskType'] = _TASKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Worker = _reflection.GeneratedProtocolMessageType('Worker', (_message.Message,), {
  'DESCRIPTOR' : _WORKER,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Worker)
  })
_sym_db.RegisterMessage(Worker)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Task)
  })
_sym_db.RegisterMessage(Task)

WordList = _reflection.GeneratedProtocolMessageType('WordList', (_message.Message,), {
  'DESCRIPTOR' : _WORDLIST,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.WordList)
  })
_sym_db.RegisterMessage(WordList)

MapResults = _reflection.GeneratedProtocolMessageType('MapResults', (_message.Message,), {

  'MapResultsEntry' : _reflection.GeneratedProtocolMessageType('MapResultsEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPRESULTS_MAPRESULTSENTRY,
    '__module__' : 'protos.mapreduce_pb2'
    # @@protoc_insertion_point(class_scope:grpc.MapResults.MapResultsEntry)
    })
  ,
  'DESCRIPTOR' : _MAPRESULTS,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.MapResults)
  })
_sym_db.RegisterMessage(MapResults)
_sym_db.RegisterMessage(MapResults.MapResultsEntry)

ReduceResults = _reflection.GeneratedProtocolMessageType('ReduceResults', (_message.Message,), {

  'ReduceResultsEntry' : _reflection.GeneratedProtocolMessageType('ReduceResultsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REDUCERESULTS_REDUCERESULTSENTRY,
    '__module__' : 'protos.mapreduce_pb2'
    # @@protoc_insertion_point(class_scope:grpc.ReduceResults.ReduceResultsEntry)
    })
  ,
  'DESCRIPTOR' : _REDUCERESULTS,
  '__module__' : 'protos.mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ReduceResults)
  })
_sym_db.RegisterMessage(ReduceResults)
_sym_db.RegisterMessage(ReduceResults.ReduceResultsEntry)


_MAPRESULTS_MAPRESULTSENTRY._options = None
_REDUCERESULTS_REDUCERESULTSENTRY._options = None

_MAPREDUCE = _descriptor.ServiceDescriptor(
  name='MapReduce',
  full_name='grpc.MapReduce',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=537,
  serialized_end=745,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_worker_task',
    full_name='grpc.MapReduce.get_worker_task',
    index=0,
    containing_service=None,
    input_type=_WORKER,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='finish_map_task',
    full_name='grpc.MapReduce.finish_map_task',
    index=1,
    containing_service=None,
    input_type=_MAPRESULTS,
    output_type=_MAPRESULTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='finish_reduce_task',
    full_name='grpc.MapReduce.finish_reduce_task',
    index=2,
    containing_service=None,
    input_type=_REDUCERESULTS,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='worker_down',
    full_name='grpc.MapReduce.worker_down',
    index=3,
    containing_service=None,
    input_type=_WORKER,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPREDUCE)

DESCRIPTOR.services_by_name['MapReduce'] = _MAPREDUCE

# @@protoc_insertion_point(module_scope)
