# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/mapreduce.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x14\n\x06Worker\x12\n\n\x02id\x18\x01 \x01(\x03\"Z\n\x04Task\x12!\n\ttask_type\x18\x01 \x01(\x0e\x32\x0e.grpc.TaskType\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x15\n\rnum_red_tasks\x18\x03 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\t\"\x1d\n\x08WordList\x12\x11\n\tword_list\x18\x01 \x03(\t\"\x86\x01\n\nMapResults\x12\x35\n\x0bmap_results\x18\x01 \x03(\x0b\x32 .grpc.MapResults.MapResultsEntry\x1a\x41\n\x0fMapResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.grpc.WordList:\x02\x38\x01\"\x98\x01\n\rReduceResults\x12>\n\x0ereduce_results\x18\x01 \x03(\x0b\x32&.grpc.ReduceResults.ReduceResultsEntry\x12\x11\n\tbucket_id\x18\x02 \x01(\x05\x1a\x34\n\x12ReduceResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01*8\n\x08TaskType\x12\x08\n\x04idle\x10\x00\x12\x07\n\x03map\x10\x01\x12\n\n\x06reduce\x10\x02\x12\r\n\tshut_down\x10\x03\x32\xd0\x01\n\tMapReduce\x12+\n\x0fget_worker_task\x12\x0c.grpc.Worker\x1a\n.grpc.Task\x12\x35\n\x0f\x66inish_map_task\x12\x10.grpc.MapResults\x1a\x10.grpc.MapResults\x12\x35\n\x12\x66inish_reduce_task\x12\x13.grpc.ReduceResults\x1a\n.grpc.Task\x12(\n\x0bworker_down\x12\x0c.grpc.Worker\x1a\x0b.grpc.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.mapreduce_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPRESULTS_MAPRESULTSENTRY._options = None
  _MAPRESULTS_MAPRESULTSENTRY._serialized_options = b'8\001'
  _REDUCERESULTS_REDUCERESULTSENTRY._options = None
  _REDUCERESULTS_REDUCERESULTSENTRY._serialized_options = b'8\001'
  _TASKTYPE._serialized_start=478
  _TASKTYPE._serialized_end=534
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _WORKER._serialized_start=41
  _WORKER._serialized_end=61
  _TASK._serialized_start=63
  _TASK._serialized_end=153
  _WORDLIST._serialized_start=155
  _WORDLIST._serialized_end=184
  _MAPRESULTS._serialized_start=187
  _MAPRESULTS._serialized_end=321
  _MAPRESULTS_MAPRESULTSENTRY._serialized_start=256
  _MAPRESULTS_MAPRESULTSENTRY._serialized_end=321
  _REDUCERESULTS._serialized_start=324
  _REDUCERESULTS._serialized_end=476
  _REDUCERESULTS_REDUCERESULTSENTRY._serialized_start=424
  _REDUCERESULTS_REDUCERESULTSENTRY._serialized_end=476
  _MAPREDUCE._serialized_start=537
  _MAPREDUCE._serialized_end=745
# @@protoc_insertion_point(module_scope)
